@startuml
'https://plantuml.com/class-diagram



class export
class item
interface arrayList
class importer

importer -> arrayList
arrayList -- item
arrayList -> export

class export {
item[] arrayList
+exportTSV()
+exportHTML()
}

class item {
serial
price
name
+setter()
+getter()
}

class importer {
filename
item[] importArrayList
+import()

}

@enduml